# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    strategy:
      matrix:
        # See:
        # https://github.com/actions/python-versions/blob/main/versions-manifest.json
        # https://downloads.python.org/pypy/versions.json
        python: [
          '3.7',
          '3.9',
          '3.10',
          '3.11.0-alpha',  # prerelease
          'pypy-3.7',
          'pypy-3.8',
        ]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Download windows-semaphore-helper
        run: Invoke-WebRequest -Uri "https://github.com/ralexander-phi/windows-semaphore-helper/releases/download/v0.1/SemaphoreHelper.exe" -OutFile SemaphoreHelper.exe
      - name: Test with pytest
        run: |
          python -m pip install -r requirements_dev.txt
          python -m pytest --cov=semaphore_win_ctypes
      - name: Lint with flake8
        run: |
          python -m pip install flake8
          python -m flake8 semaphore_win_ctypes
